### ISSUE TITLE
Token is invalid

### ISSUE THREAD

**Issue by muhamedoufi** [videosdk-live/videosdk-rtc-api-server-examples#10]
<pre>
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Firebase\JWT\JWT;
// use Monolog\DateTimeImmutable;
use Symfony\Component\Config\Definition\Exception\Exception;
use Firebase\JWT\Key;
use Ramsey\Uuid\Uuid;

 /**
    * @param Request $request
    * @return \Symfony\Component\HttpFoundation\JsonResponse
    * @Route("/generateJWTToken", name="access_token", methods={"GET"})
    */
   public function get_token(Request $request)
   {

       $apiKey = $this->getParameter('app.env.VIDEOSDK_API_KEY');
       $apiKeySecrtet = $this->getParameter('app.env.VIDEOSDK_SECRET_KEY');
       $endpoint = $this->getParameter('app.env.VIDEOSDK_API_ENDPOINT');
    //    $issuedAt = new DateTimeImmutable($useMicroseconds=true);
       $issuedAt = new \DateTimeImmutable();

       $expire = $issuedAt->modify('+24 hours')->getTimestamp();
   
    //    $payload = (object)[];
       $payload = [
            "apikey" => $apiKey,
            "permissions" => array(
                "allow_join",

            ),
            "iat" =>$issuedAt->getTimestamp(),
            "exp" => $expire,
            "email_id"=>'muhamedoufi@gmail.com',

        ];
    //    $payload->apikey = $apiKey;
    //    $payload->permissions = array(
    //        "allow_join",
    //    );
    //    $payload->iat = $issuedAt->getTimestamp();
    //    $payload->exp = $expire;
       
    //    $payload = array($payload);
    //    $payload= json_decode($payload, true);
    //    dd($payload);
       $jwt = JWT::encode($payload, $apiKeySecrtet, 'HS256');
    //    dd($jwt);
    //    $this->json(['token' => $token->toJWT(), 'room'=> $roomName], 200);
    //    $decoded = JWT::decode($jwt, new Key($apiKey, 'HS256'));
    //    dd($decoded);
       return $this->json(array("generatedtoken" => $jwt));
   }

 /**
    * @param Request $request
    * @return \Symfony\Component\HttpFoundation\JsonResponse
    * @Route("/createMeeting", name="createMeeting", methods={"POST"})
    */
    public function createMeeting(Request $request)
    {

     
        $apiKey = $this->getParameter('app.env.VIDEOSDK_API_KEY');
        $apiKeySecrtet = $this->getParameter('app.env.VIDEOSDK_SECRET_KEY');
        $endpoint = $this->getParameter('app.env.VIDEOSDK_API_ENDPOINT');
        // $data = json_decode(file_get_contents('php://input') , true);
        // dd($data);
       // $token = $data["token"];
        $token = $request->headers->get('Authorization');
        // headers->get('Authorization')
        // $token = $request->getContent();
        $data = json_decode($request->getContent(), true);
        // dd($data);
        // dd($token);
        $curl = curl_init();
        // dd($curl);
        // dd($endpoint);
        curl_setopt_array($curl, array(
            CURLOPT_URL => $endpoint . '/rooms',
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_HTTPHEADER => array(
                'Authorization: Barer' . $token,
                'Content-Type: application/json'
            ) ,
        ));
        $curl_error = curl_getinfo($curl);
        $response = curl_exec($curl);
        if ($response ===false) {
            throw new Exception(curl_error($curl),curl_errno($curl));
        }
        dd($response);
        // dd($curl_error);

        curl_close($curl);
        // return $response;
        return $this->json($response);
    }

</pre>

**Comment by ahmedbhesaniya97** [comment]
Hey @muhamedoufi.
Can you DM me token in our Discord server https://discord.gg/Xbnhj92G.
So that we can identify the cause.

**Comment by muhamedoufi** [comment]
> Hey @muhamedoufi. Can you DM me token in our Discord server https://discord.gg/Xbnhj92G. So that we can identify the cause.

I enter to discourd but the first time that i use discourd.
what i can do ?

**Comment by ahmedbhesaniya97** [comment]
Did you enter in our server ?

**Comment by muhamedoufi** [comment]
> @muhamedoufi Did you enter in our server ?

yes my name is fi
